# Generated by Django 4.2.1 on 2023-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='timeOfRent',
            field=models.DurationField(),
        ),
    ]
