# Generated by Django 4.2.1 on 2023-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_ordermodel_timeofrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body',
            field=models.CharField(choices=[('sed', 'Седан'), ('cross', 'Кроссовер'), ('stwag', 'Универсал'), ('sport', 'Седан'), ('hatch', 'Хэтчбек'), ('convert', 'Кабриолет'), ('miniv', 'Минивэн'), ('cup', 'Купе')], max_length=20),
        ),
    ]
