# Generated by Django 4.2.1 on 2023-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_carmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('MERC', 'Mercedes'), ('AUD', 'Audi'), ('MAZD', 'Mazda'), ('VOLV', 'Volvo')], max_length=20),
        ),
    ]
