# Generated by Django 4.2.1 on 2023-05-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_price',
            field=models.BigIntegerField(default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.BigIntegerField(default=40, null=True),
        ),
    ]
