# Generated by Django 4.2.1 on 2023-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Кроссовер', 'Кроссовер'), ('Универсал', 'Универсал'), ('Спорт', 'Седан'), ('Хэтчбек', 'Хэтчбек'), ('Кабриолет', 'Кабриолет'), ('Минивэн', 'Минивэн'), ('Купе', 'Купе')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Mazda', 'Mazda'), ('Volvo', 'Volvo')], max_length=20),
        ),
    ]
