# Generated by Django 4.2.1 on 2023-05-16 13:40

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_carmodel_body_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automodel',
            name='number',
            field=models.CharField(max_length=9, validators=[mainapp.models.car_number_validator]),
        ),
        migrations.AlterField(
            model_name='automodel',
            name='status',
            field=models.CharField(choices=[('На заказе', 'На заказе'), ('Свободна', 'Свободна'), ('В ремонте', 'В ремонте'), ('На обслуживании', 'На обслуживании')], max_length=20),
        ),
    ]
