# Generated by Django 4.2.1 on 2023-05-16 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_alter_automodel_number_alter_automodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automodel',
            name='usageCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='usageCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='usageCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penaltymodel',
            name='usageCount',
            field=models.IntegerField(default=0),
        ),
    ]
