# Generated by Django 4.2.1 on 2023-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_ordermodel_timeofrent_ordermodel_dateendfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='discounts',
            field=models.ManyToManyField(null=True, to='mainapp.discountmodel'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='penalties',
            field=models.ManyToManyField(null=True, to='mainapp.penaltymodel'),
        ),
    ]
