# Generated by Django 4.2.1 on 2023-05-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_clientmodel_discounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='discounts',
            field=models.ManyToManyField(default=None, null=True, to='mainapp.discountmodel'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='penalties',
            field=models.ManyToManyField(default=None, null=True, to='mainapp.penaltymodel'),
        ),
    ]
