# Generated by Django 4.2.1 on 2023-05-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_clientmodel_discounts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='car',
            new_name='auto',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='penalties',
        ),
    ]
