# Generated by Django 4.2.1 on 2023-05-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_ordermodel_dateendfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='discounts',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='mainapp.discountmodel'),
        ),
    ]
