# Generated by Django 4.2.1 on 2023-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_clientmodel_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automodel',
            name='status',
            field=models.CharField(choices=[('На заказе', 'На заказе'), ('Свободна', 'Свободна'), ('В ремонте', 'В ремонте'), ('На обслуживании', 'На обслуживании')], default='Свободна', max_length=20),
        ),
    ]
