# Generated by Django 4.2.1 on 2023-05-30 12:24

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_automodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='phone',
            field=models.CharField(max_length=15, validators=[mainapp.models.phone_number_validator]),
        ),
    ]
