# Generated by Django 4.2.1 on 2023-09-15 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
