# Generated by Django 4.2.1 on 2023-09-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_news_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsModel',
        ),
    ]
